### ISSUE TITLE
_esni prefix is challenging for DNS wildcard syntax with TXT type

### ISSUE THREAD

**Issue by mcmanus** [tlswg/draft-ietf-tls-esni#79] opened 2018-07-19 19:34 UTC
if you dynamically syntehsize a whole bunch of names in example.com you would probably use a *.example.com a/aaaa configuration to do so and give them all the same addresses.

but you can't do the same things for TXT records with the _esni prefix..  basically _esni.*.example.com doesn't do the trick (rfc 4592).

initially I viewed this as a configuration and implementation issue because queries and responses do not carry the * at all - the records are synthesized on demand from this config.

however, the wildcard is part of AXFR which forms an open interface between resolvers so its syntax and meaning is quite reasonably standardized and should be considered.

**Comment by kazuho** [comment] 2018-07-19 19:55
> however, the wildcard is part of AXFR which forms an open interface between resolvers

Minor point but I am not sure if AXFR is something that is exposed to the resolvers. My understanding is standardized interface for synchronizing authoritative servers. So this will be an issue only for websites that use a DNS that either depends on AXFR (or in other ways depend on the vocabulary of the AXFR).

I agree that it would be preferable to address the issue.

**Comment by mcmanus** [comment] 2018-07-19 20:08
my thought here is that axfr represents an interface between, potentially,
different implementations so we should try and respect that to whatever
extent is possible.

**Comment by kazuho** [comment] 2018-07-19 22:55
My view of the issue is that we can support all the models that we need to support if we adopt #73 so that ESNIKeys will be distributed using a dedicated type with a prefix.

The patterns we need to consider are the combination of three types of DNS records (i.e. single-host, APEX, wildcard) and a boolean indicating if DNS is maintained by someone other than the CDN.

The table below illustrates how you could configure the DNS on each case. There are certain cases in which you could use CNAME instead of A / ESNI.

|**DNS operated by**|**single-host**|**APEX**|**wildcard**|
|:---|:---|:---|:---|
|**CDN**|host IN A addr<br>_esni.host IN ESNI ...|@ IN A addr<br>_esni IN ESNI ...|* IN A addr<br>* IN ESNI ...<sup>1</sup>|
|**not CDN**|host IN CNAME addr<br>_esni.host CNAME _esni.cdn|@ IN A cdn-ipaddr<br>_esni IN CNAME _esni.cdn|* IN CNAME _all.cdn<sup>1<sup>|

1: You will be required to create _esni records for all hosts that you specify explicitly, if it is necessary to disable ESNI for those hosts (or if those hosts use different ESNI keys).

**Comment by chris-wood** [comment] 2019-03-06 22:43
Fixed in #144.

**Closed by chris-wood** 2019-03-06 22:43 UTC
