### ISSUE TITLE
Use SRV for fronting server selection

### ISSUE THREAD

**Issue by huitema** [tlswg/draft-ietf-tls-esni#180] opened 2019-07-29 17:46 UTC
I think that the current ESNI record is maybe a little too
complicated. The ESNI key is really a property of the public server, yet
the ESNI record is defined as a property of the hidden server. If the
public server rolls a new key, all the ESNI records of all the hidden
servers that mentioned the old key need to be updated. I think it would
be simpler to have the ESNI record as a property of the public server,
and to just have a pointer to the public server in the context of the
hidden server. May an SRV record. The chain would be something like:

1) Look up whether the SRV record for _esni._tcp.hidden.example.com

2) If there are such records, select the appropriate public server, say
public.example.net

3) Look up ESNI, A, AAAA for public.example.net

In that architecture, there is no need to encode the public server name
in the ESNI record. I think there will be several advantages. The ESNI
record's TTL can be set to the lifetime of the key. The SRV record's TTL
can be set to the expected lifetime of the relation between 'hidden" and
"public". If the SRV lifetime is long enough, the value can be
efficiently cached by the client. If multiple clients share the same
hidden server, the ESNI record is fetched only once, and can be cached.
At connection time, the client would only need to query the A/AAAA
records of the public server, i.e. exactly the same DNS transaction as
an access to the public server.

**Comment by huitema** [comment] 2019-07-29 17:49
Issue #139 proposes something similar, using PTR records. I think the semantic of SRV records is closer to what we need.

**Comment by huitema** [comment] 2019-07-29 17:51
The practical consequence would be to remove the "public name" component from the ESNI record.

**Comment by kazuho** [comment] 2019-07-30 07:21
IIRC, the principle that we have so far followed is that ESNI should not introduce additional latency (i.e. roundtrip). TLS WG has spent great effort in reducing the number of roundtrips spent during the handshake. It would be very unfortunate to add latency with ESNI.

Also, I am not sure how much the issue is a practical concern, because I'd assume that most if not all of the DNS records of the hidden hostnames would be a CNAME to the public name. The ESNI record would be associated to that public name.

To rephrase, the ESNI record would be associated to the public name in the current scheme.

**Comment by huitema** [comment] 2019-07-30 16:20
I agree that if the typical implementation is to have the hidden server name point to the public server with a CNAME, then the current record format is just fine. We may want to document this hidden CNAME assumption in the document.

On the other hand, I am still not convinced that CNAME is the proper tool. We definitely want to use DNSSEC to sign the record pointing from hidden to public. Otherwise, it becomes very simple to inject a false record pointing to a compromised public server, and then track clients. At a minimum, if we expect the hidden servers to use CNAME, we should explain how to use DNSSEC to secure that.

Apart from DNSSEC, the other feature that we want is the support for multiple public servers, in case one of them is blocked. I don't think that CNAME can do that. In practice, the simplest way will be to have multiple ESNI records listed directly in the context of the hidden server. That works, and doing DNSSEC is straightforward. But it implies replication of the public server ESNI record in many places, which brings in the issues of managing replication.

**Comment by kazuho** [comment] 2019-07-31 07:22
@huitema I think that elaborating on the expected practice is a good idea.

> Apart from DNSSEC, the other feature that we want is the support for multiple public servers, in case one of them is blocked.

While I appreciate the possibility, I am not sure if it is a good idea to endorse ESNI to be used as a tool to circumvent blocking. Because doing so would lead to ESNI being blocked. Rather, my preference goes to promoting ESNI as a tool for protecting privacy.

**Comment by chris-wood** [comment] 2019-11-02 01:02
Fixed by #187.

**Closed by chris-wood** 2019-11-02 01:02 UTC
