### ISSUE TITLE
cardinality of ECHOConfig vs. HTTPSSVC

### ISSUE THREAD

**Issue by sftcd** [tlswg/draft-ietf-tls-esni#219] opened 2020-04-12 20:32 UTC
A server can publish multuple HTTPSSVC RRs. Each of those RRs can contain multiple ECHOConfigContent values (i.e. multiple public keys and public_names). I don't see a real need for two different ways to publish more than one public key for a given server. There is a minor efficiency benefit in terms of the number of octets published in the DNS, but there is a lot of additional complexity in terms of code, and if nobody really publishes multiple public keys in one RR value, then that code is likely where we'll find CVEs. Reducing down to one public key per RR value also reduces the complexity when writing code to create/publish RRs.

I think we have to support multiple RR values, because that's how the DNS works, and so the one to drop is the multiple public keys in one ECHOConfigs. IOW, I'd suggest one ECHOConfig has exactly one public key.

**Comment by davidben** [comment] 2020-04-13 16:03
A single ECHOConfig already has only one public key from https://github.com/tlswg/draft-ietf-tls-esni/pull/201 and the HPKE bits.

I'm guessing you meant ECHOConfigs? There are multiple ECHOConfig values in a single ECHOConfigs, which came from https://github.com/tlswg/draft-ietf-tls-esni/pull/200. (Gosh, that was a terrible name. My bad. Maybe we should rename it?) I think the rationale there still holds? The problem is that an HTTPSSVC RR implies transport-level decisions, while not every ECHOConfig can be consumed by your TLS logic. Folding them together means transport connect needs to be aware of the exact ECHO capabilities. For instance, the origin could advertise:

* route1.example.com echo=ECHOv1
* route2.example.com echo=ECHOv2

The logic picking HTTPSSVC routes no longer gets a free choice. It must be aware of the TLS layer's capabilities (down to mandatory extensions and HPKE code points). ECHOConfigs means the expectation is:

* route1.example.com echo={ECHOv1,ECHOv2}
* route2.example.com echo={ECHOv2,ECHOv2}

Now you pick a route freely and pass the entire opaque ECHO blob to TLS to interpret. Of course, one could still advertise:

* route1.example.com echo={ECHOv1}
* route2.example.com echo={ECHOv2}

But you're no longer forced to explode it out like that, so we can say an ECHOv1-only client that happens to pick route2 can act as if route1 didn't exist. I.e. we set an expectation that all your routes must be equally capable. (Just as we have that expectation elsewhere. If route1 only speaks TLS 1.0, you're not getting TLS's downgrade protection because the attacker can always redirect you to the less secure config.)

**Comment by sftcd** [comment] 2020-04-13 19:35
On 13/04/2020 17:03, David Benjamin wrote:
> 
> But you're no longer forced to explode it out like that, so we can 
> say an ECHOv1-only client that happens to pick route2 can act as if 
> route1 didn't exist. I.e. we set an expectation that all your routes 
> must be equally capable. (Just as we have that expectation 
> elsewhere.

Gotta admit I'm not at all getting what you're saying,
sorry. As-is, clients need to write the code to handle
multiple keys (and all other variations possible) at
both levels, or if not, then we're missing text in the
spec saying what doesn't need to be supported.

I don't see a real benefit in that complexity.

**Comment by chris-wood** [comment] 2020-04-27 21:52
As per today's call, we're closing this due to the simplifications it brings for client implementations, in particular around collating all logic about ECHOConfig compatibility inside the TLS stack without the need for additional interfaces.

**Closed by chris-wood** 2020-04-27 21:52 UTC
