### ISSUE TITLE
Replace config_id with a server-chosen key_id

### ISSUE THREAD

**Issue by chris-wood** [tlswg/draft-ietf-tls-esni#375] opened 2021-01-26 01:46 UTC
After very useful discussion with many folks, it seems now is the time to remove config_id. There are a couple reasons to do this:

- Servers need to know the correct hash function to use when computing the ID, and possibly need to compute multiple IDs for a given public key (since a config can have multiple hash-based KDFs), which is somewhat annoying and redundant.
- The entire ECHConfig is already authenticated, so using a hash to prove that the client made a determination based on the correct config contents is unnecessary.
- Servers will likely only ever have a small handful of keys in motion at any point in time, so anything more than a couple of bits to identify one of said keys is excessive.
- ... there are probably more.

The original design [had a server-chosen label, but we removed it](https://github.com/tlswg/draft-ietf-tls-esni/pull/43). (Oops!) It seems we're now in a better position to bring this back, but with some simplifications.

**Comment by sftcd** [comment] 2021-01-26 01:56
Hiya,

On 26/01/2021 01:46, Christopher Wood wrote:
> After very useful discussion with many folks, 

Can you send a pointer to those discussions? (Sorry, I seem
to have missed 'em;-)

Ta,
S.

**Comment by chris-wood** [comment] 2021-01-26 02:29
> Can you send a pointer to those discussions? (Sorry, I seem to have missed 'em;-)

Sorry -- these were informal conversations off-list.

**Comment by sftcd** [comment] 2021-01-26 02:35
On 26/01/2021 02:29, Christopher Wood wrote:
>> Can you send a pointer to those discussions? (Sorry, I seem to have missed 'em;-)
> 
> Sorry -- these were informal conversations off-list.

Ah. That's a recurring problem. And even this exchange is
actually off-list.

Can we please fix that? I think I've whined about that a
few times now, and would hope that continual whining is
not a requirement;-)

S.


> 
>

**Comment by ekr** [comment] 2021-01-26 02:38
> Can we please fix that? I think I've whined about that a
few times now, and would hope that continual whining is
not a requirement;-)

Fix what? A few of us had a private conversation about some ideas and came to the conclusion that it would be better to replace the hash with a key_id. Then Chris and Martin brought it to a Github issue. This is precisely in line with the WG consensus to use Github issue discussion mode, as documented in 8874 S 5.3.

**Comment by sftcd** [comment] 2021-01-26 03:02
On 26/01/2021 02:38, ekr wrote:
> 
> Fix what? A few of us had a private conversation about some ideas 

I'm guessing that was a private discussion amongst what could
well be described as the usual suspects or an old-boys club
(or are a few of you "many folks?"). Correct me if I'm wrong
but that had zero visibility and zero traceability and zero
accountability for anyone who isn't one of those old boys.

And yet we're zapping a field in a PDU from what was declared
as an "implementation draft" a day or so after one major
deployment declared they had an interop target. To me, that
smells of disrespect for outsiders tbh.

You can probably guess what I think about that state of
affairs:-)

> and
> came to the conclusion that it would be better to replace the hash
> with a key_id. Then Chris and Martin brought it to a Github issue.
> This is precisely in line with the WG consensus to use Github issue
> discussion mode, as documented in 8874 S 5.3.
I don't buy that tbh. Chris' mail was presented as a
conclusion, from a wg-chair following a private discussion
that for sure excluded some implementers. (Me being one,
albeit a not very good one:-)

And you yourself are an ex WG-chair so I'd guess you ought
also care about exclusivity here. What gain is there from
that kind of behaviour? I don't see it myself.

IMO, there is no need nor benefit from being so exclusive
wrt this spec, yet that is what is happening and has been
for a few years. I'd encourage those of you who may be
"old-boys" to consider whether or not that is really the
best way to proceed. IMO - it is not, you lose way more than
you might think you gain, almost all the time.

Cheers,
S.

PS: I don't disagree with the outcome, though have opinions
on what -10 might contain. I do very much dislike the awful
process, which is my point here.

**Comment by seanturner** [comment] 2021-01-28 16:56
@sftcd I would completely agree with you had the proposed PR been merged and the associated issue been closed. That has not happened. Further, it appears that you might be reading a bit more into Chris' issue summary than is really there. He is not acting in his WG chair capacity here because he is an author; I know he knows that and I really hope you can give him the benefit of the doubt here so that we do not have to suffer the "no WG chair hat on" in every message/post.

The process, as I see it, is pretty darn near normal. Somebody files an issue and optionally (but preferably) files a PR to address said issue. Discussion ensues amd if substantive it's taken to the list. The PR may or may not be modified based on that discussion. If consensus is reached, the PR is merged and the issue is closed.

We are at the discussion point. Can we do that now?

**Comment by sftcd** [comment] 2021-01-28 17:20
On 28/01/2021 16:56, Sean Turner wrote:
> @sftcd I would completely agree with you had the proposed PR been
> merged and the associated issue been closed. That has not happened.
> Further, it appears that you might be reading a bit more into Chris'
> issue summary than is really there. He is not acting in his WG chair
> capacity here because he is an author; I know he knows that and I
> really hope you can give him the benefit of the doubt here so that we
> do not have to suffer the "no WG chair hat on" in every
> message/post.

Perhaps it'd be better to not start a mail with "After very
useful discussion with many folks, it seems now is the time to remove 
config_id." in cases where that discussion was
purely private? I can understand it being hard to keep track
with the various tools, but for me, that still reads as a
decision being announced even if that was not the intent.

Sorry for being over-sensitive to this but IMO there is a
history and ongoing tendency with this spec for a subset of
people to act as if they and not the IETF/WG have change
control. I fully accept that they are not deliberately
aiming to avoid having to garner WG consensus but consider
that ongoing instances of carelessness such as the above
demonstrate that there is an insider/outsider thing going
on here.

S.

> 
> The process, as I see it, is pretty darn near normal. Somebody files
> an issue and optionally (but preferably) files a PR to address said
> issue. Discussion ensues amd if substantive it's taken to the list.
> The PR may or may not be modified based on that discussion. If
> consensus is reached, the PR is merged and the issue is closed.
> 
> We are at the discussion point. Can we do that now?
>

**Closed** 2021-02-15 20:08 UTC
